{
  "openapi": "3.0.0",
  "info": {
    "title": "サンプル",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:8000"
    }
  ],
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "required": [
          "name",
          "email",
          "password",
          "is_admin"
        ],
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "email_verified_at": {
            "type": "string"
          },
          "is_admin": {
            "type": "boolean"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          },
          "deleted_at": {
            "type": "string"
          }
        }
      },
      "EmailReset": {
        "type": "object",
        "required": [
          "user_id",
          "new_email",
          "token"
        ],
        "properties": {
          "id": {
            "type": "integer"
          },
          "user_id": {
            "type": "integer"
          },
          "new_email": {
            "type": "string"
          },
          "token": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          }
        }
      },
      "Post": {
        "type": "object",
        "required": [
          "user_id",
          "text"
        ],
        "properties": {
          "id": {
            "type": "integer"
          },
          "user_id": {
            "type": "integer"
          },
          "text": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Comment": {
        "type": "object",
        "required": [
          "post_id",
          "user_id",
          "text"
        ],
        "properties": {
          "id": {
            "type": "integer"
          },
          "post_id": {
            "type": "integer"
          },
          "user_id": {
            "type": "integer"
          },
          "text": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          }
        }
      }
    }
  },
  "paths": {
    "/sanctum/csrf-cookie": {
      "get": {
        "tags": [
          "Auth"
        ],
        "description": "CSRFトークンを生成する。",
        "responses": {
          "204": {
            "description": "成功",
            "headers": {
              "XSRF-TOKEN": {
                "schema": {
                  "type": "string",
                  "example": "XSRF-TOKEN=abc123;"
                },
                "description": "CSRFトークン"
              }
            }
          }
        }
      }
    },
    "/register": {
      "post": {
        "tags": [
          "Auth"
        ],
        "description": "ユーザーを登録し、ログインを行う。",
        "requestBody": {
          "content": {
            "application/json:": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Test User"
                  },
                  "email": {
                    "type": "string",
                    "example": "test@example.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "password"
                  },
                  "password_confirmation": {
                    "type": "string",
                    "example": "password"
                  }
                },
                "required": [
                  "name",
                  "email",
                  "password",
                  "password_confirmation"
                ]
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "成功"
          },
          "419": {
            "description": "CORS not allowed"
          },
          "422": {
            "description": "validation error"
          }
        }
      }
    },
    "/restore-token": {
      "post": {
        "tags": [
          "Auth"
        ],
        "description": "メールアドレスとパスワードをもとにユーザーを検索し、対象ユーザーの復活用トークンを取得する。",
        "requestBody": {
          "content": {
            "application/json:": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "test@example.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "password"
                  }
                },
                "required": [
                  "email",
                  "password"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "restore_token": {
                      "type": "string",
                      "example": "2UWS1KkuBUAe0oot9hOYtJrqZUUnUykRR6EruXJU9vL4TnMm2CXLwpNFoIAj"
                    }
                  }
                }
              }
            }
          },
          "419": {
            "description": "CORS not allowed"
          },
          "422": {
            "description": "validation error"
          }
        }
      }
    },
    "/restore/{token}": {
      "post": {
        "tags": [
          "Auth"
        ],
        "description": "トークンをもとにユーザーを検索し、対象ユーザーを復活させる。",
        "parameters": [
          {
            "description": "ユーザー復活用トークン",
            "in": "path",
            "name": "token",
            "required": true,
            "schema": {
              "type": "string",
              "example": "2UWS1KkuBUAe0oot9hOYtJrqZUUnUykRR6EruXJU9vL4TnMm2CXLwpNFoIAj"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "成功"
          },
          "419": {
            "description": "CORS not allowed"
          },
          "422": {
            "description": "validation error"
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": [
          "Auth"
        ],
        "description": "ログインを行う。",
        "requestBody": {
          "content": {
            "application/json:": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "test@example.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "password"
                  }
                },
                "required": [
                  "email",
                  "password"
                ]
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "成功"
          },
          "419": {
            "description": "CORS not allowed"
          },
          "422": {
            "description": "authentication failed"
          }
        }
      }
    },
    "/forgot-password": {
      "post": {
        "tags": [
          "Auth"
        ],
        "description": "指定されたメールアドレスに対して、パスワードリセットメールを送信する。",
        "requestBody": {
          "content": {
            "application/json:": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "test@example.com"
                  }
                },
                "required": [
                  "email"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "パスワードリセットメールを送信しました。"
                    }
                  }
                }
              }
            }
          },
          "419": {
            "description": "CORS not allowed"
          },
          "422": {
            "description": "validation error"
          }
        }
      }
    },
    "/reset-password": {
      "post": {
        "tags": [
          "Auth"
        ],
        "description": "パスワードをリセットする。",
        "requestBody": {
          "content": {
            "application/json:": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "test@example.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "password"
                  },
                  "password_confirmation": {
                    "type": "string",
                    "example": "password"
                  },
                  "token": {
                    "type": "string",
                    "example": "781f2cbe7c692028c0d49c4ef208387362a984442263a91850f8a0e55c6e2d47"
                  }
                },
                "required": [
                  "email",
                  "password",
                  "password_confirmation",
                  "token"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "パスワードをリセットしました。"
                    }
                  }
                }
              }
            }
          },
          "419": {
            "description": "CORS not allowed"
          },
          "422": {
            "description": "validation error"
          }
        }
      }
    },
    "/verify-email/{id}/{hash}": {
      "get": {
        "tags": [
          "Auth"
        ],
        "description": "メールアドレスを検証済みとする。",
        "parameters": [
          {
            "description": "ユーザーのID",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          },
          {
            "description": "メールアドレス認証トークン",
            "in": "path",
            "name": "hash",
            "required": true,
            "schema": {
              "type": "string",
              "example": "567159d622ffbb50b11b0efd307be358624a26ee"
            }
          }
        ],
        "responses": {
          "302": {
            "description": "redirect to HOME"
          }
        }
      }
    },
    "/email/verification-notification": {
      "post": {
        "tags": [
          "Auth"
        ],
        "description": "メールアドレス確認通知を送信する。",
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "verification-link-sent"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/logout": {
      "post": {
        "tags": [
          "Auth"
        ],
        "description": "ログアウトを行う。",
        "responses": {
          "204": {
            "description": "成功"
          }
        }
      }
    },
    "/api/user": {
      "get": {
        "tags": [
          "User"
        ],
        "description": "ログインユーザーを取得する。",
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "examples": {
                  "general": {
                    "summary": "一般ユーザー実行時のレスポンス",
                    "value": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer",
                          "example": 1
                        },
                        "name": {
                          "type": "string",
                          "example": "山田一郎"
                        }
                      }
                    }
                  },
                  "admin": {
                    "summary": "管理者ユーザー実行時のレスポンス",
                    "value": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer",
                          "example": 1
                        },
                        "name": {
                          "type": "string",
                          "example": "山田一郎"
                        },
                        "email": {
                          "type": "string",
                          "example": "test@example.co.jp"
                        },
                        "email_verified_at": {
                          "type": "string",
                          "example": "2022-01-02 00:00:00"
                        },
                        "is_admin": {
                          "type": "boolean",
                          "example": true
                        },
                        "created_at": {
                          "type": "string",
                          "example": "2022-01-01 00:00:00"
                        },
                        "updated_at": {
                          "type": "string",
                          "example": "2022-01-02 00:00:00"
                        },
                        "deleted_at": {
                          "type": "string",
                          "example": null
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/users": {
      "get": {
        "tags": [
          "User"
        ],
        "description": "ユーザーを取得する。",
        "parameters": [
          {
            "description": "ページの指定",
            "in": "query",
            "name": "page",
            "required": false,
            "schema": {
              "type": "integer",
              "example": 1
            }
          },
          {
            "description": "1ページに表示する件数",
            "in": "query",
            "name": "per_page",
            "required": false,
            "schema": {
              "type": "integer",
              "example": 5
            }
          },
          {
            "description": "検索キーワード",
            "in": "query",
            "name": "keyword",
            "required": false,
            "schema": {
              "type": "string",
              "example": "郎"
            }
          },
          {
            "description": "論理削除されていないデータのみに絞り込み",
            "in": "query",
            "name": "active_only",
            "required": false,
            "schema": {
              "type": "boolean",
              "example": false
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "examples": {
                  "general": {
                    "summary": "一般ユーザー実行時のレスポンス",
                    "value": {
                      "type": "object",
                      "properties": {
                        "total": {
                          "type": "integer",
                          "example": 50
                        },
                        "per_page": {
                          "type": "integer",
                          "example": 5
                        },
                        "current_page": {
                          "type": "integer",
                          "example": 1
                        },
                        "last_page": {
                          "type": "integer",
                          "example": 10
                        },
                        "first_item": {
                          "type": "integer",
                          "example": 1
                        },
                        "last_item": {
                          "type": "integer",
                          "example": 5
                        },
                        "has_more_pages": {
                          "type": "boolean",
                          "example": true
                        },
                        "data": {
                          "type": "array",
                          "example": [
                            {
                              "id": 1,
                              "name": "山田一郎"
                            },
                            {
                              "id": 2,
                              "name": "田中二郎"
                            },
                            {
                              "id": 3,
                              "name": "中田三郎"
                            },
                            {
                              "id": 4,
                              "name": "田山四郎"
                            },
                            {
                              "id": 5,
                              "name": "中村五郎"
                            }
                          ]
                        }
                      }
                    }
                  },
                  "admin": {
                    "summary": "管理者ユーザー実行時のレスポンス",
                    "value": {
                      "type": "object",
                      "properties": {
                        "total": {
                          "type": "integer",
                          "example": 50
                        },
                        "per_page": {
                          "type": "integer",
                          "example": 5
                        },
                        "current_page": {
                          "type": "integer",
                          "example": 1
                        },
                        "last_page": {
                          "type": "integer",
                          "example": 10
                        },
                        "first_item": {
                          "type": "integer",
                          "example": 1
                        },
                        "last_item": {
                          "type": "integer",
                          "example": 5
                        },
                        "has_more_pages": {
                          "type": "boolean",
                          "example": true
                        },
                        "data": {
                          "type": "array",
                          "example": [
                            {
                              "id": 1,
                              "name": "山田一郎",
                              "email": "test@example.co.jp",
                              "email_verified_at": "2022-01-02 00:00:00",
                              "is_admin": true,
                              "created_at": "2022-01-01 00:00:00",
                              "updated_at": "2022-01-02 00:00:00",
                              "deleted_at": null
                            },
                            {
                              "id": 2,
                              "name": "田中二郎",
                              "email": "test2@example.co.jp",
                              "email_verified_at": "2022-01-02 00:00:00",
                              "is_admin": false,
                              "created_at": "2022-01-01 00:00:00",
                              "updated_at": "2022-01-02 00:00:00",
                              "deleted_at": null
                            },
                            {
                              "id": 3,
                              "name": "中田三郎",
                              "email": "test3@example.co.jp",
                              "email_verified_at": "2022-01-02 00:00:00",
                              "is_admin": false,
                              "created_at": "2022-01-01 00:00:00",
                              "updated_at": "2022-01-02 00:00:00",
                              "deleted_at": null
                            },
                            {
                              "id": 4,
                              "name": "田山四郎",
                              "email": "test4@example.co.jp",
                              "email_verified_at": "2022-01-02 00:00:00",
                              "is_admin": false,
                              "created_at": "2022-01-01 00:00:00",
                              "updated_at": "2022-01-02 00:00:00",
                              "deleted_at": null
                            },
                            {
                              "id": 5,
                              "name": "中村五郎",
                              "email": "test5@example.co.jp",
                              "email_verified_at": "2022-01-02 00:00:00",
                              "is_admin": false,
                              "created_at": "2022-01-01 00:00:00",
                              "updated_at": "2022-01-02 00:00:00",
                              "deleted_at": null
                            }
                          ]
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/users/{id}": {
      "get": {
        "tags": [
          "User"
        ],
        "description": "指定したユーザーを取得する。",
        "parameters": [
          {
            "description": "ユーザーのID",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "examples": {
                  "general": {
                    "summary": "一般ユーザー実行時のレスポンス",
                    "value": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer",
                          "example": 1
                        },
                        "name": {
                          "type": "string",
                          "example": "山田一郎"
                        }
                      }
                    }
                  },
                  "admin": {
                    "summary": "管理者ユーザー実行時のレスポンス",
                    "value": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer",
                          "example": 1
                        },
                        "name": {
                          "type": "string",
                          "example": "山田一郎"
                        },
                        "email": {
                          "type": "string",
                          "example": "test@example.co.jp"
                        },
                        "email_verified_at": {
                          "type": "string",
                          "example": "2022-01-02 00:00:00"
                        },
                        "is_admin": {
                          "type": "boolean",
                          "example": true
                        },
                        "created_at": {
                          "type": "string",
                          "example": "2022-01-01 00:00:00"
                        },
                        "updated_at": {
                          "type": "string",
                          "example": "2022-01-02 00:00:00"
                        },
                        "deleted_at": {
                          "type": "string",
                          "example": null
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "User"
        ],
        "description": "指定したユーザーを更新する。",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "山田一郎"
                  }
                },
                "required": [
                  "name"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "examples": {
                  "general": {
                    "summary": "一般ユーザー実行時のレスポンス",
                    "value": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer",
                          "example": 1
                        },
                        "name": {
                          "type": "string",
                          "example": "山田一郎"
                        }
                      }
                    }
                  },
                  "admin": {
                    "summary": "管理者ユーザー実行時のレスポンス",
                    "value": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer",
                          "example": 1
                        },
                        "name": {
                          "type": "string",
                          "example": "山田一郎"
                        },
                        "email": {
                          "type": "string",
                          "example": "test@example.co.jp"
                        },
                        "email_verified_at": {
                          "type": "string",
                          "example": "2022-01-02 00:00:00"
                        },
                        "is_admin": {
                          "type": "boolean",
                          "example": true
                        },
                        "created_at": {
                          "type": "string",
                          "example": "2022-01-01 00:00:00"
                        },
                        "updated_at": {
                          "type": "string",
                          "example": "2022-01-02 00:00:00"
                        },
                        "deleted_at": {
                          "type": "string",
                          "example": null
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "User"
        ],
        "description": "指定したユーザーを論理削除する。",
        "parameters": [
          {
            "description": "ユーザーのID",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "password": {
                    "type": "string",
                    "example": "password"
                  }
                },
                "required": [
                  "password"
                ]
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "成功"
          },
          "403": {
            "description": "権限エラー",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "許可されていない操作です。"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/users/{id}/update-permission": {
      "put": {
        "tags": [
          "User"
        ],
        "description": "指定したユーザーの権限を更新する。",
        "parameters": [
          {
            "description": "ユーザーのID",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "is_admin": {
                    "type": "boolean",
                    "example": true
                  }
                },
                "required": [
                  "is_admin"
                ]
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "成功"
          }
        }
      }
    },
    "/api/users/{id}/restore": {
      "post": {
        "tags": [
          "User"
        ],
        "description": "指定したユーザーを復活させる。",
        "parameters": [
          {
            "description": "ユーザーのID",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "204": {
            "description": "成功"
          },
          "403": {
            "description": "権限エラー",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "許可されていない操作です。"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/email-resets/send-reset-link": {
      "post": {
        "tags": [
          "EmailReset"
        ],
        "description": "新しいメールアドレスを一時テーブルに保存し、メールアドレス確認通知を送信する。",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "new_email": {
                    "type": "string",
                    "example": "test@example.co.jp"
                  }
                },
                "required": [
                  "new_email"
                ]
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "成功"
          }
        }
      }
    },
    "/api/email-resets/{token}": {
      "put": {
        "tags": [
          "EmailReset"
        ],
        "description": "トークンを用いてユーザーを取得し、対象ユーザーのメールアドレスを更新する。",
        "parameters": [
          {
            "description": "メールアドレス更新用トークン",
            "in": "path",
            "name": "token",
            "required": true,
            "schema": {
              "type": "string",
              "example": "4vIzesVBxRvrugX6uSxdENL2QkaL56iCE0aHlZbzVI7iNYEy46TIXHaNHZGx"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "成功"
          }
        }
      }
    },
    "/api/password-resets": {
      "put": {
        "tags": [
          "PasswordReset"
        ],
        "description": "ログインユーザーのパスワードを更新する。",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "password": {
                    "type": "string",
                    "example": "password"
                  },
                  "new_password": {
                    "type": "string",
                    "example": "new_password"
                  },
                  "new_password_confirmation": {
                    "type": "string",
                    "example": "new_password"
                  }
                },
                "required": [
                  "password",
                  "new_password",
                  "new_password_confirmation"
                ]
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "成功"
          }
        }
      }
    },
    "/api/posts": {
      "get": {
        "tags": [
          "Post"
        ],
        "description": "投稿を取得する。",
        "parameters": [
          {
            "description": "ページの指定",
            "in": "query",
            "name": "page",
            "required": false,
            "schema": {
              "type": "integer",
              "example": 1
            }
          },
          {
            "description": "1ページに表示する件数",
            "in": "query",
            "name": "per_page",
            "required": false,
            "schema": {
              "type": "integer",
              "example": 5
            }
          },
          {
            "description": "検索キーワード",
            "in": "query",
            "name": "keyword",
            "required": false,
            "schema": {
              "type": "string",
              "example": "テスト"
            }
          },
          {
            "description": "投稿者による絞り込み",
            "in": "query",
            "name": "user_ids[]",
            "required": false,
            "schema": {
              "type": "array",
              "example": [
                1,
                2,
                3,
                4,
                5
              ]
            }
          },
          {
            "description": "並び順の指定",
            "in": "query",
            "name": "order",
            "required": false,
            "schema": {
              "type": "string",
              "example": "popular"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "total": {
                      "type": "integer",
                      "example": 50
                    },
                    "per_page": {
                      "type": "integer",
                      "example": 5
                    },
                    "current_page": {
                      "type": "integer",
                      "example": 1
                    },
                    "last_page": {
                      "type": "integer",
                      "example": 10
                    },
                    "first_item": {
                      "type": "integer",
                      "example": 1
                    },
                    "last_item": {
                      "type": "integer",
                      "example": 5
                    },
                    "has_more_pages": {
                      "type": "boolean",
                      "example": true
                    },
                    "data": {
                      "type": "array",
                      "example": [
                        {
                          "id": 5,
                          "user_id": 3,
                          "text": "テスト",
                          "comments": [
                            {
                              "id": 1,
                              "post_id": 1,
                              "user_id": 1,
                              "text": "テスト",
                              "created_by": "山田一郎",
                              "created_at": "2022-01-01 00:00:00"
                            },
                            {
                              "id": 2,
                              "post_id": 1,
                              "user_id": 1,
                              "text": "テスト",
                              "created_by": "山田一郎",
                              "created_at": "2022-01-02 00:00:00"
                            }
                          ],
                          "created_by": "中田三郎",
                          "created_at": "2022-01-03 00:00:00",
                          "updated_at": "2022-01-04 00:00:00"
                        },
                        {
                          "id": 4,
                          "user_id": 3,
                          "text": "テスト",
                          "comments": [],
                          "created_by": "中田三郎",
                          "created_at": "2022-01-02 00:00:00",
                          "updated_at": "2022-01-02 00:00:00"
                        },
                        {
                          "id": 3,
                          "user_id": 3,
                          "text": "テスト",
                          "comments": [],
                          "created_by": "中田三郎",
                          "created_at": "2022-01-01 00:00:00",
                          "updated_at": "2022-01-02 00:00:00"
                        },
                        {
                          "id": 2,
                          "user_id": 2,
                          "text": "テスト",
                          "comments": [],
                          "created_by": "田中二郎",
                          "created_at": "2022-01-01 00:00:00",
                          "updated_at": "2022-01-02 00:00:00"
                        },
                        {
                          "id": 1,
                          "user_id": 1,
                          "text": "テスト",
                          "comments": [],
                          "created_by": "山田一郎",
                          "created_at": "2022-01-01 00:00:00",
                          "updated_at": "2022-01-02 00:00:00"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Post"
        ],
        "description": "投稿を作成する。",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "text": {
                    "type": "string",
                    "example": "テスト"
                  }
                },
                "required": [
                  "text"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer",
                      "example": 1
                    },
                    "user_id": {
                      "type": "integer",
                      "example": 1
                    },
                    "text": {
                      "type": "string",
                      "example": "テスト"
                    },
                    "comments": [
                      {
                        "id": 1,
                        "post_id": 1,
                        "user_id": 1,
                        "text": "テスト",
                        "created_by": "山田一郎",
                        "created_at": "2022-01-01 00:00:00"
                      },
                      {
                        "id": 2,
                        "post_id": 1,
                        "user_id": 1,
                        "text": "テスト",
                        "created_by": "山田一郎",
                        "created_at": "2022-01-02 00:00:00"
                      }
                    ],
                    "created_by": {
                      "type": "string",
                      "example": "山田一郎"
                    },
                    "created_at": {
                      "type": "string",
                      "example": "2022-01-01 00:00:00"
                    },
                    "updated_at": {
                      "type": "string",
                      "example": "2022-01-02 00:00:00"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Post"
        ],
        "description": "指定した投稿を更新する。",
        "parameters": [
          {
            "description": "投稿のID",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "text": {
                    "type": "string",
                    "example": "テスト"
                  }
                },
                "required": [
                  "text"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer",
                      "example": 1
                    },
                    "user_id": {
                      "type": "integer",
                      "example": 1
                    },
                    "text": {
                      "type": "string",
                      "example": "テスト"
                    },
                    "comments": [
                      {
                        "id": 1,
                        "post_id": 1,
                        "user_id": 1,
                        "text": "テスト",
                        "created_by": "山田一郎",
                        "created_at": "2022-01-01 00:00:00"
                      },
                      {
                        "id": 2,
                        "post_id": 1,
                        "user_id": 1,
                        "text": "テスト",
                        "created_by": "山田一郎",
                        "created_at": "2022-01-02 00:00:00"
                      }
                    ],
                    "created_by": {
                      "type": "string",
                      "example": "山田一郎"
                    },
                    "created_at": {
                      "type": "string",
                      "example": "2022-01-01 00:00:00"
                    },
                    "updated_at": {
                      "type": "string",
                      "example": "2022-01-02 00:00:00"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/posts/{id}": {
      "get": {
        "tags": [
          "Post"
        ],
        "description": "指定した投稿を取得する。",
        "parameters": [
          {
            "description": "投稿のID",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer",
                      "example": 1
                    },
                    "user_id": {
                      "type": "integer",
                      "example": 1
                    },
                    "text": {
                      "type": "string",
                      "example": "テスト"
                    },
                    "comments": [
                      {
                        "id": 1,
                        "post_id": 1,
                        "user_id": 1,
                        "text": "テスト",
                        "created_by": "山田一郎",
                        "created_at": "2022-01-01 00:00:00"
                      },
                      {
                        "id": 2,
                        "post_id": 1,
                        "user_id": 1,
                        "text": "テスト",
                        "created_by": "山田一郎",
                        "created_at": "2022-01-02 00:00:00"
                      }
                    ],
                    "created_by": {
                      "type": "string",
                      "example": "山田一郎"
                    },
                    "created_at": {
                      "type": "string",
                      "example": "2022-01-01 00:00:00"
                    },
                    "updated_at": {
                      "type": "string",
                      "example": "2022-01-02 00:00:00"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Post"
        ],
        "description": "指定した投稿を削除する。",
        "parameters": [
          {
            "description": "投稿のID",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "204": {
            "description": "成功"
          }
        }
      }
    },
    "/api/comments": {
      "get": {
        "tags": [
          "Comment"
        ],
        "description": "コメントを取得する。",
        "parameters": [
          {
            "description": "取得するデータの指定",
            "in": "query",
            "name": "cursor",
            "required": false,
            "schema": {
              "type": "string",
              "example": "eyJjb21tZW50cy5pZCI6MTUsIl9wb2ludHNUb05leHRJdGVtcyI6dHJ1ZX0"
            }
          },
          {
            "description": "投稿のID",
            "in": "query",
            "name": "post_id",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "total": {
                      "type": "integer",
                      "example": 50
                    },
                    "next_cursor": {
                      "type": "string",
                      "example": "eyJjb21tZW50cy5pZCI6MTUsIl9wb2ludHNUb05leHRJdGVtcyI6dHJ1ZX0"
                    },
                    "prev_cursor": {
                      "type": "string",
                      "example": null
                    },
                    "data": {
                      "type": "array",
                      "example": [
                        {
                          "id": 1,
                          "post_id": 1,
                          "user_id": 1,
                          "text": "テスト",
                          "created_by": "山田一郎",
                          "created_at": "2022-01-01 00:00:00"
                        },
                        {
                          "id": 2,
                          "post_id": 1,
                          "user_id": 1,
                          "text": "テスト",
                          "created_by": "山田一郎",
                          "created_at": "2022-01-02 00:00:00"
                        },
                        {
                          "id": 3,
                          "post_id": 1,
                          "user_id": 1,
                          "text": "テスト",
                          "created_by": "山田一郎",
                          "created_at": "2022-01-03 00:00:00"
                        },
                        {
                          "id": 4,
                          "post_id": 1,
                          "user_id": 1,
                          "text": "テスト",
                          "created_by": "山田一郎",
                          "created_at": "2022-01-04 00:00:00"
                        },
                        {
                          "id": 5,
                          "post_id": 1,
                          "user_id": 1,
                          "text": "テスト",
                          "created_by": "山田一郎",
                          "created_at": "2022-01-05 00:00:00"
                        },
                        {
                          "id": 6,
                          "post_id": 1,
                          "user_id": 2,
                          "text": "テスト",
                          "created_by": "田中二郎",
                          "created_at": "2022-01-06 00:00:00"
                        },
                        {
                          "id": 7,
                          "post_id": 1,
                          "user_id": 2,
                          "text": "テスト",
                          "created_by": "田中二郎",
                          "created_at": "2022-01-07 00:00:00"
                        },
                        {
                          "id": 8,
                          "post_id": 1,
                          "user_id": 2,
                          "text": "テスト",
                          "created_by": "田中二郎",
                          "created_at": "2022-01-08 00:00:00"
                        },
                        {
                          "id": 9,
                          "post_id": 1,
                          "user_id": 2,
                          "text": "テスト",
                          "created_by": "田中二郎",
                          "created_at": "2022-01-09 00:00:00"
                        },
                        {
                          "id": 10,
                          "post_id": 1,
                          "user_id": 2,
                          "text": "テスト",
                          "created_by": "田中二郎",
                          "created_at": "2022-01-10 00:00:00"
                        },
                        {
                          "id": 11,
                          "post_id": 1,
                          "user_id": 3,
                          "text": "テスト",
                          "created_by": "中田三郎",
                          "created_at": "2022-01-11 00:00:00"
                        },
                        {
                          "id": 12,
                          "post_id": 1,
                          "user_id": 3,
                          "text": "テスト",
                          "created_by": "中田三郎",
                          "created_at": "2022-01-12 00:00:00"
                        },
                        {
                          "id": 13,
                          "post_id": 1,
                          "user_id": 3,
                          "text": "テスト",
                          "created_by": "中田三郎",
                          "created_at": "2022-01-13 00:00:00"
                        },
                        {
                          "id": 14,
                          "post_id": 1,
                          "user_id": 3,
                          "text": "テスト",
                          "created_by": "中田三郎",
                          "created_at": "2022-01-14 00:00:00"
                        },
                        {
                          "id": 15,
                          "post_id": 1,
                          "user_id": 3,
                          "text": "テスト",
                          "created_by": "中田三郎",
                          "created_at": "2022-01-15 00:00:00"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Comment"
        ],
        "description": "コメントを作成する。",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "post_id": {
                    "type": "integer",
                    "example": 1
                  },
                  "text": {
                    "type": "string",
                    "example": "テスト"
                  }
                },
                "required": [
                  "post_id",
                  "text"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer",
                      "example": 1
                    },
                    "post_id": {
                      "type": "integer",
                      "example": 1
                    },
                    "user_id": {
                      "type": "integer",
                      "example": 1
                    },
                    "text": {
                      "type": "string",
                      "example": "テスト"
                    },
                    "created_by": {
                      "type": "string",
                      "example": "山田一郎"
                    },
                    "created_at": {
                      "type": "string",
                      "example": "2022-01-01 00:00:00"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/comments/{id}": {
      "delete": {
        "tags": [
          "Comment"
        ],
        "description": "指定したコメントを削除する。",
        "parameters": [
          {
            "description": "コメントのID",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "204": {
            "description": "成功"
          }
        }
      }
    }
  }
}